# Generated by Django 2.2.1 on 2019-05-14 21:21

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='商品类名')),
                ('isDelete', models.BooleanField(default=False, verbose_name='逻辑删除标志')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='商品名称')),
                ('pic', models.ImageField(upload_to='df_goods', verbose_name='商品图片')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='商品价格')),
                ('isDelete', models.BooleanField(default=False, verbose_name='逻辑删除标志')),
                ('unit', models.CharField(max_length=20, verbose_name='商品单位')),
                ('sale', models.IntegerField(verbose_name='商品销量')),
                ('stock', models.IntegerField(verbose_name='商品库存')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='上架时间')),
                ('description', models.CharField(max_length=200, verbose_name='商品描述')),
                ('content', ckeditor.fields.RichTextField(verbose_name='商品详情')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='df_goods.TypeInfo', verbose_name='所属类别')),
            ],
        ),
    ]
